#!/usr/bin/env python3
"""Generate reviewed OpenCode subagents from harness-specific source files."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


DEFAULT_AGENT_SOURCES = [
    "opencode/agent-sources/code-reviewer.md",
    "opencode/agent-sources/software-architect.md",
    "opencode/agent-sources/security-engineer.md",
    "opencode/agent-sources/database-optimizer.md",
    "opencode/agent-sources/accessibility-auditor.md",
    "opencode/agent-sources/evidence-reader.md",
    "opencode/agent-sources/luna-implementer.md",
    "opencode/agent-sources/luna-reader.md",
]

READ_ONLY_AGENTS = {
    "accessibility_auditor",
    "code_reviewer",
    "database_optimizer",
    "evidence_analyst",
    "evidence_reader",
    "security_engineer",
    "software_architect",
    "luna_reader",
}

BROAD_READER_AGENTS = {
    "evidence_reader",
    "luna_reader",
}

IMPLEMENTATION_AGENTS = {
    "luna_implementer",
}

GENERATED_MARKER = "<!-- Generated by scripts/generate-opencode-agents.py"


def parse_frontmatter(path: Path) -> tuple[dict[str, str], str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError(f"{path} does not start with YAML front matter")

    marker = "\n---\n"
    end = text.find(marker, len("---\n"))
    if end == -1:
        raise ValueError(f"{path} has unterminated YAML front matter")

    frontmatter = text[len("---\n") : end]
    body = text[end + len(marker) :].strip()
    metadata: dict[str, str] = {}

    for line in frontmatter.splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        key, separator, value = line.partition(":")
        if not separator:
            continue
        value = value.strip()
        if (value.startswith('"') and value.endswith('"')) or (
            value.startswith("'") and value.endswith("'")
        ):
            value = value[1:-1]
        metadata[key.strip()] = value

    return metadata, body


def agent_name(display_name: str) -> str:
    name = display_name.lower()
    name = re.sub(r"[^a-z0-9]+", "_", name)
    return re.sub(r"_+", "_", name).strip("_")


def yaml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def render_agent(source: Path, repo_root: Path, name: str) -> str:
    metadata, body = parse_frontmatter(source)
    description = metadata["description"]
    vibe = metadata.get("vibe")
    instructions = body
    if vibe:
        instructions = f"{instructions}\n\n## Operating Style\n\n{vibe}"

    permission_lines = [
        '  "*": deny',
        "  question: deny",
        "  read:",
        '    "*": allow',
        "    .env: deny",
        '    ".env.*": deny',
        '    "*.env": deny',
        '    "*.env.*": deny',
        "    .envrc: deny",
        '    ".env.d/**": deny',
        '    "*.envrc": deny',
        "    .env.example: allow",
        '    "*.env.example": allow',
        "  external_directory:",
        '    "~/**": allow',
        '    "~/.aws/**": deny',
        '    "~/.azure/**": deny',
        '    "~/.cargo/**": deny',
        '    "~/.config/**": allow',
        '    "~/.docker/**": deny',
        '    "~/.gem/**": deny',
        '    "~/.git-credentials": deny',
        '    "~/.gnupg/**": deny',
        '    "~/.kube/**": deny',
        '    "~/.local/share/**": deny',
        '    "~/.netrc": deny',
        '    "~/.npmrc": deny',
        '    "~/.oci/**": deny',
        '    "~/.pypirc": deny',
        '    "~/.ssh/**": deny',
        '    "~/.terraform.d/**": deny',
        '    "~/Library/**": deny',
        '    "~/.local/share/opencode/worktree/**": allow',
        '    "/private/var/folders/**/T/opencode/**": allow',
        "  glob: allow",
    ]
    if name in BROAD_READER_AGENTS:
        permission_lines.extend([
            "  grep: allow",
            "  ast_grep: allow",
            "  text_read: allow",
            "  skill: deny",
        ])
    else:
        permission_lines.extend([
            "  grep: deny",
            "  text_read: allow",
            "  skill: allow",
        ])
    if name in READ_ONLY_AGENTS:
        permission_lines.extend([
            "  edit: deny",
            "  bash: deny",
        ])
    elif name in IMPLEMENTATION_AGENTS:
        permission_lines.extend([
            "  edit: allow",
            "  bash:",
            '    "*": allow',
            '    "rm -rf *": ask',
            '    "sudo *": ask',
            '    "git *": ask',
            '    "git diff": allow',
            '    "git diff *": allow',
            '    "git log": allow',
            '    "git log *": allow',
            '    "git show": allow',
            '    "git show *": allow',
            '    "git status": allow',
            '    "git status *": allow',
            '    "git reset --hard": ask',
            '    "git reset --hard *": ask',
            '    "git clean *": ask',
            '    "git commit *": deny',
            '    "git push": deny',
            '    "git push *": deny',
        ])
    else:
        raise ValueError(f"unknown generated agent permission profile: {name}")
    permission_lines.extend([
        "  task: deny",
        "  todowrite: deny",
        "  advisor: deny",
    ])

    relative_source = source.relative_to(repo_root)
    frontmatter = [
        "---",
        f"description: {yaml_string(description)}",
        "mode: subagent",
        "permission:",
        *permission_lines,
        "---",
    ]
    generated_notice = f"{GENERATED_MARKER} from {relative_source}. -->"
    return "\n".join([*frontmatter, "", generated_notice, "", instructions, ""])


def expected_agents(repo_root: Path) -> dict[Path, str]:
    expected: dict[Path, str] = {}
    seen_names: dict[str, Path] = {}
    output_dir = repo_root / "opencode" / "agents"

    for relative_source in DEFAULT_AGENT_SOURCES:
        source = repo_root / relative_source
        metadata, _ = parse_frontmatter(source)
        name = agent_name(metadata["name"])
        if name in seen_names:
            raise ValueError(
                f"duplicate OpenCode agent name {name!r}: "
                f"{seen_names[name]} and {source}"
            )
        seen_names[name] = source
        expected[output_dir / f"{name}.md"] = render_agent(
            source, repo_root, name
        )

    return expected


def generated_files(output_dir: Path) -> set[Path]:
    return {
        path
        for path in output_dir.glob("*.md")
        if GENERATED_MARKER in path.read_text(encoding="utf-8")
    }


def check(repo_root: Path) -> int:
    expected = expected_agents(repo_root)
    stale = generated_files(repo_root / "opencode" / "agents") - set(expected)
    mismatched = [
        path
        for path, rendered in expected.items()
        if not path.exists() or path.read_text(encoding="utf-8") != rendered
    ]

    if mismatched or stale:
        for path in mismatched:
            print(f"OUTDATED {path.relative_to(repo_root)}")
        for path in sorted(stale):
            print(f"STALE {path.relative_to(repo_root)}")
        return 1

    print(f"Validated {len(expected)} generated OpenCode agents")
    return 0


def generate(repo_root: Path) -> None:
    expected = expected_agents(repo_root)
    output_dir = repo_root / "opencode" / "agents"
    output_dir.mkdir(parents=True, exist_ok=True)

    for destination, rendered in expected.items():
        destination.write_text(rendered, encoding="utf-8")

    for stale in generated_files(output_dir) - set(expected):
        stale.unlink()

    print(f"Generated {len(expected)} OpenCode agents in opencode/agents")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Validate generated output without writing files.",
    )
    args = parser.parse_args()
    repo_root = Path(__file__).resolve().parents[1]

    if args.check:
        raise SystemExit(check(repo_root))
    generate(repo_root)


if __name__ == "__main__":
    main()
